### ISSUE TITLE
Test set up install error

### ISSUE THREAD

**Issue by tomwayson** [tomdale/ember-network#14]
I'm trying to follow the set up in the [Testing section of the README](https://github.com/tomdale/ember-network#testing). When I ran `ember install fetch-mock ember-browserify` I get this error: `Install failed. Could not find addon with name: fetch-mock`

I think this should be:

```
npm install fetch-mock
ember install ember-browserify
```

Right?

**Comment by locks** [comment]
Fixed by https://github.com/tomdale/ember-network/pull/13, thanks for reporting!
