### ISSUE TITLE
deprecate in-favour of ember-fetch

### ISSUE THREAD

**Issue by stefanpenner** [tomdale/ember-network#17]
* its actively maintained
* its the original (not sure why the work here wasn't a contribution to ember-fetch)

---

I suspect `ember-network` aim(s|ed) to be more lofty, supporting other protocols. Maybe we should  resurrect when it does support more, or is that inbound?

**Comment by rwjblue** [comment]
Agreed.  Having two competing but identical solutions is very confusing...

**Comment by acorncom** [comment]
This is now deprecated
