### ISSUE TITLE
App build broken

### ISSUE THREAD

**Issue by vlascik** [tomdale/ember-network#3]
Build failed.
The Broccoli Plugin: [object Object] failed with:
undefined

The broccoli plugin was instantiated at:
undefined

Similar to https://github.com/ember-cli/ember-cli/issues/5571 
Win10, cli 2.4.2, node 5.7.0, npm 5.6.0

**Comment by tomdale** [comment]
Is this only on Windows or can I repro on my Mac? Is it possible to get a stacktrace?

**Comment by vlascik** [comment]
Not sure about the Mac, don't have any nearby, but the other issue mentioned was on Windows as well.
There is no stacktrace in console, just this error. 
I'm not sure how to set the breakpoint at the point where broccoli processes this addon, it doesn't happen in its index.js as far as I can tell. I might take a closer look at how broccoli works tomorrow, any pointers would be great.
Weird thing is that the same thing happens on ember-network and ember-fetch, which I assume both use the same underlying libraries.
